# Generated by Django 3.0.7 on 2020-07-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='flag',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='letter',
            name='letter_topic',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='letter',
            name='right',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='letter',
            name='context',
            field=models.CharField(max_length=512),
        ),
    ]
