# Generated by Django 3.0.7 on 2020-07-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200709_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('xinli_id', models.IntegerField()),
                ('letter_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Xinli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('context', models.CharField(max_length=512)),
                ('editor', models.CharField(max_length=64)),
                ('date', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='letter',
            name='flag',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='letter',
            name='right',
            field=models.IntegerField(),
        ),
    ]
