# Generated by Django 3.0.7 on 2020-07-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200709_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='letter',
            name='delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xinli',
            name='delete',
            field=models.IntegerField(default=0),
        ),
    ]
