# Generated by Django 3.0.7 on 2020-07-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200710_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='letter_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='collect',
            name='username',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='collect',
            name='xinli_id',
            field=models.IntegerField(default=''),
        ),
    ]
