# Generated by Django 3.0.7 on 2020-07-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200710_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='collect_letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64)),
                ('letter_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='collect',
        ),
    ]
