# Generated by Django 3.0.7 on 2020-07-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200727_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect_letter',
            name='letter_id',
        ),
        migrations.AddField(
            model_name='collect_letter',
            name='xinli_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collect_letter',
            name='username',
            field=models.CharField(default='', max_length=52),
        ),
    ]
