# Generated by Django 3.0.7 on 2020-07-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200727_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect_letter',
            name='username',
            field=models.CharField(default='', max_length=56),
        ),
    ]
