# Generated by Django 3.0.7 on 2020-07-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200727_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='collect_xinli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=56)),
                ('xinli_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='reply_letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=56)),
                ('letter_id', models.IntegerField(default=0)),
                ('context', models.CharField(max_length=512)),
            ],
        ),
        migrations.RenameField(
            model_name='collect_letter',
            old_name='xinli_id',
            new_name='letter_id',
        ),
        migrations.AlterField(
            model_name='collect_letter',
            name='username',
            field=models.CharField(default='', max_length=64),
        ),
    ]
