# Generated by Django 3.0.7 on 2020-07-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200730_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply_letter',
            name='read_flag',
            field=models.IntegerField(default=0),
        ),
    ]
