# Generated by Django 3.0.7 on 2020-07-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_reply_letter_read_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply_letter',
            name='collect_flag',
            field=models.IntegerField(default=0),
        ),
    ]
