# Generated by Django 3.0.7 on 2020-08-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_reply_letter_collect_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply_letter',
            name='check',
            field=models.FloatField(default=''),
        ),
    ]
