# Generated by Django 3.0.7 on 2020-08-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_reply_letter_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply_letter',
            name='check',
            field=models.CharField(default='', max_length=56),
        ),
    ]
