# Generated by Django 3.0.7 on 2020-08-04 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20200804_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply_letter',
            old_name='check',
            new_name='probability',
        ),
    ]
