# Generated by Django 3.0.7 on 2020-08-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20200804_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='probability',
            field=models.CharField(default='', max_length=56),
        ),
    ]
