# Generated by Django 3.0.7 on 2020-08-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_letter_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='report',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply_letter',
            name='report',
            field=models.IntegerField(default=0),
        ),
    ]
